# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
# https://docs.aws.amazon.com/codebuild/latest/userguide/getting-started-cli-create-build-spec.html

version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 5.0
      python: 3.8
    commands:
      # Check PowerShell Version
      - pwsh -command '$PSVersionTable'

      # check python version
      - python --version

      # Check available environment variables in the build
      - pwsh -command 'Get-ChildItem env:'

      # Configure AWS defaults using the configuration script added to the Docker Image.
      - pwsh -command './CodeBuild/configure_aws_credential.ps1'

      # Installing PowerShell Modules from PSGallery
      - pwsh -command '$ProgressPreference = 'SilentlyContinue' ; ./CodeBuild/IntegrationTest/install_modules.ps1'

      # Install Python packages
      - pip install pip -U --quiet
      - pip install -r ./lambdafunctions/python/requirements.txt --quiet

  pre_build:
    commands:
      # Set webhook
      - pwsh -command './CodeBuild/IntegrationTest/set_webhooks.ps1'

  build:
    commands:
      - echo THE BUILD

  post_build:
    commands:
      - echo THE POSTBUILD

# artifacts:
#   files:
#     - cloudformation/**/*
#     - CodeBuild/**/*