# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
# https://docs.aws.amazon.com/codebuild/latest/userguide/getting-started-cli-create-build-spec.html

version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 5.0
      python: 3.8
    commands:
      # Check PowerShell Version
      - pwsh -command '$PSVersionTable'


      # check python version
      - python --version

      # Check available variables in the build
      # - pwsh -command 'Get-Variable'

      # Check available environment variables in the build
      - pwsh -command 'Get-ChildItem env:'

      # Configure AWS defaults using the configuration script added to the Docker Image.
      - pwsh -command './CodeBuild/configure_aws_credential.ps1'

      # Installing PowerShell Modules from PSGallery
      - pwsh -command './CodeBuild/install_modules.ps1'

      # Install Python packages
      - pip install pip -U
      - pip install -r ./lambdafunctions/python/requirements.txt

  pre_build:
    commands:
      - echo THE PREBUILD
      # Validate CloudFormation Templates
      # - pwsh -command '
      #     Import-Module Pester;
      #     $pesterConfiguration = [PesterConfiguration]::new();
      #     $pesterConfiguration.Run.Exit = $true;
      #     $pesterConfiguration.Run.Path = "./CodeBuild/UnitTestAndBuild/Validate-CFNTemplates.Tests.ps1";
      #     $pesterConfiguration.Output.Verbosity = "Detailed";
      #     Invoke-Pester -Configuration $pesterConfiguration'
#
      # # Validate Json files
      # - pwsh -command '
      #     Import-Module Pester;
      #     $pesterConfiguration = [PesterConfiguration]::new();
      #     $pesterConfiguration.Run.Exit = $true;
      #     $pesterConfiguration.Run.Path = "./CodeBuild/UnitTestAndBuild/Validate-JSONConfigurations.Tests.ps1";
      #     $pesterConfiguration.Output.Verbosity = "Detailed";
      #     Invoke-Pester -Configuration $pesterConfiguration'
  build:
    commands:
      - echo THE BUILD

  post_build:
    commands:
      - echo THE POSTBUILD

# artifacts:
#   files:
#     - cloudformation/**/*
#     - CodeBuild/**/*