---
AWSTemplateFormatVersion: '2010-09-09'

Description: 'AUTOMATED: pythonLambdaExample Serverless Deployment Logic'

Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  ServiceName:
    Type: String
    Description: 'Name of the service that will be used to tag each resource.'

  StackTag:
    Type: String
    Description: An environment tag for this stack. Used to differentiate what resource need or should be created.

Resources:

  # https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md#awsserverlessfunction
  pythonLambdaExample:
    Type: 'AWS::Serverless::Function'
    # DependsOn:
    Properties:
      CodeUri: src
      Description: 'Example Python Lambda'
      Environment:
        Variables:
          AN_ENV_VARIABLE: 'TestEnvironmentVariable'
      Handler: handlers.lambda_handler
      MemorySize: 1024
      Runtime: python3.8
      Timeout: 900
      # Events:
      #   UpdatePBXQueue:
      #     Type: SQS
      #     Properties:
      #       Queue: !GetAtt queName.Arn
      #       BatchSize: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        # - S3ReadPolicy:
        #     BucketName:
        # - S3CrudPolicy:
        #     BucketName:
        # - Statement:
        #     - Sid: SecretsOauthRetrieve
        #       Effect: Allow
        #       Action:
        #         - secretsmanager:GetSecretValue
        #       Resource:
        #         - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:SecretName'
        #     - Sid: QueName
        #       Effect: Allow
        #       Action:
        #         - sqs:SendMessage
        #         - sqs:ListQueues
        #         - sqs:ListDeadLetterSourceQueues
        #         - sqs:ReceiveMessage
        #         - sqs:GetQueueAttributes
        #         - sqs:ListQueueTags
        #       Resource: !GetAtt queName.Arn
      Tags:
        ServiceName: !Ref ServiceName
        StackName: !Ref AWS::StackName

  #https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html
  pythonLambdaExampleLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: pythonLambdaExample
    Properties:
      LogGroupName: !Sub '/aws/lambda/${pythonLambdaExample}'
      RetentionInDays: 7

Outputs:
  pythonLambdaExample:
    Description: Arn for pythonLambdaExample Lambda
    Value: !GetAtt pythonLambdaExample.Arn
