AWSTemplateFormatVersion: '2010-09-09'
Description: 'AUTOMATED: pyTgBudgetBot Serverless Deployment Logic'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  ServiceName:
    Type: String
    Description: 'Name of the service that will be used to tag each resource.'

  StackTag:
    Type: String
    Description: An environment tag for this stack. Used to differentiate what resource need or should be created.
Resources:
    TestLambdaPolicy:
        Type: "AWS::IAM::ManagedPolicy"
        Properties:
            ManagedPolicyName: "TestLambdaExecutionRole"
            Path: "/service-role/"
            PolicyDocument: !Sub |
                {
                    "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Effect": "Allow",
                            "Action": [
                                "logs:CreateLogGroup",
                                "logs:CreateLogStream",
                                "logs:PutLogEvents"
                            ],
                            "Resource": [
                                "arn:aws:logs:*:*:*"
                            ]
                        },
                        {
                            "Effect": "Allow",
                            "Action": [
                                "kms:Decrypt"
                            ],
                            "Resource": [
                                "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/2cfefa65-a316-4706-a598-5e0b8cb057e9"
                            ]
                        }
                    ]
                }
    TestLambdaRole:
        Type: "AWS::IAM::Role"
        Properties:
            Path: "/service-role/"
            RoleName: "TestLambdaRole"
            AssumeRolePolicyDocument: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":[\"lambda.amazonaws.com\",\"edgelambda.amazonaws.com\"]},\"Action\":\"sts:AssumeRole\"}]}"
            MaxSessionDuration: 3600
            ManagedPolicyArns:
              - !Ref TestLambdaPolicy
    TestLambda:
        Type: 'AWS::Serverless::Function'
        Properties:
          CodeUri:
            Bucket: pytgbudgetbot-514215195183-artifacts
            Key: pkg.zip
          Description: ""
          FunctionName: !Sub "${ServiceName}testLambda"
          Handler: handlers.test_handler
          MemorySize: 1024
          Role: !GetAtt TestLambdaRole.Arn
          Runtime: python3.9
          Timeout: 900
          Environment:
              Variables:
                  TEST: '{{resolve:ssm:/tgbots/fleetmorsel/test2}}'
                  BOT_TOKEN: ''
                  CHAT_ID: ''
                  TG_URL: 'api.telegram.org'
                  CALLBACK_TABLE: 'CallbackTable'
                  DATA_TABLE: 'DataTable'
                  BOT_NAME: 'FleetMorselBot'
          Tags:
            ServiceName: !Ref ServiceName
            StackName: !Ref AWS::StackName
    TestLambdaRestApi:
          Type: "AWS::ApiGateway::RestApi"
          Properties:
              Name: TestLambdaRestApi
              ApiKeySourceType: "HEADER"
              Description: An API Gateway with a Lambda Integration
              EndpointConfiguration:
                  Types:
                    - "REGIONAL"
    TestLambdaMethod:
        Type: "AWS::ApiGateway::Method"
        Properties:
            RestApiId: !Ref TestLambdaRestApi
            ResourceId: !GetAtt TestLambdaRestApi.RootResourceId
            HttpMethod: "ANY"
            AuthorizationType: "NONE"
            ApiKeyRequired: false
            RequestParameters: {}
            MethodResponses:
              -
                ResponseModels:
                    "application/json": "Empty"
                StatusCode: "200"
            Integration:
                ContentHandling: "CONVERT_TO_TEXT"
                IntegrationHttpMethod: "POST"
                IntegrationResponses:
                  -
                    ResponseTemplates: {}
                    StatusCode: "200"
                PassthroughBehavior: "WHEN_NO_MATCH"
                TimeoutInMillis: 29000
                Type: "AWS_PROXY"
                Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${TestLambda}/invocations"
    TestLambdaStage:
        Type: AWS::ApiGateway::Stage
        Properties:
          DeploymentId: !Ref TestLambdaDeployment
          Description: Lambda API Stage v0
          RestApiId: !Ref TestLambdaRestApi
          StageName: 'v0'
    TestLambdaDeployment:
        Type: AWS::ApiGateway::Deployment
        DependsOn: TestLambdaMethod
        Properties:
          Description: Lambda API Deployment
          RestApiId: !Ref TestLambdaRestApi
    LambdaPermission:
        Type: "AWS::Lambda::Permission"
        Properties:
            Action: "lambda:InvokeFunction"
            FunctionName: !GetAtt TestLambda.Arn
            Principal: "apigateway.amazonaws.com"
            SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${TestLambdaRestApi}/*/*/"

Outputs:
  TestLambdaEndpoint:
    Description: API Gateway endpoint that will be used to configure Telegram bot webhooks
    Value: !Sub "https://${TestLambdaRestApi}.execute-api.${AWS::Region}.amazonaws.com/${TestLambdaStage}/"